### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Marisa89** [millanek/fineRADstructure#1]
Good morning, 
I am having a problem installing fineRADstructure in ubuntu 17.10. 
Following the instructions in fineRADstructure I get this error after make:
> make
CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.14 -I m4 -I ./eigen/ 
/bin/bash: aclocal-1.14: command not found
Makefile:559: recipe for target 'aclocal.m4' failed
make: *** [aclocal.m4] Error 127

I have aclocal-1.15 and automake-1.15 installed on my computer. 

I checked online what could I do and finally I did this:
> autoreconf --force --install
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:17: installing 'config/compile'
Makefile.am: error: required file './NEWS' not found
parallel-tests: installing 'config/test-driver'
autoreconf: automake failed with exit status: 1

I created the ./NEWS file and run autoreconf again

>autoreconf
aclocal: warning: couldn't open directory 'm4': No such file or directory

I created an empty directory called m4 and this time autoreconf worked, but after running ./configure and make i got this error:

>make
...
In file included from state.cpp:4:0:
/usr/include/c++/7/bits/locale_facets_nonio.tcc: In member function ‘_InIter std::__cxx11::time_get<_CharT, _InIter>::_M_extract_name(std::__cxx11::time_get<_CharT, _InIter>::iter_type, std::__cxx11::time_get<_CharT, _InIter>::iter_type, int&, const _CharT**, std::size_t, std::ios_base&, std::ios_base::iostate&) const’:
rng.h:12:18: error: expected unqualified-id before ‘(’ token
 #define min(a,b) ((a) <= (b) ? (a) : (b))
                  ^
/usr/include/c++/7/bits/locale_conv.h: In member function ‘bool std::wbuffer_convert<_Codecvt, _Elem, _Tr>::_M_conv_get()’:
rng.h:12:18: error: expected unqualified-id before ‘(’ token
 #define min(a,b) ((a) <= (b) ? (a) : (b))
                  ^
rng.h:12:18: error: expected unqualified-id before ‘(’ token
 #define min(a,b) ((a) <= (b) ? (a) : (b))
                  ^
Makefile:762: recipe for target 'finestructure-state.o' failed
make: *** [finestructure-state.o] Error 1

I am a novice in this so I don't really know what else I can do. I installed fineRADstructure in my mac and I didn't have any kind of problems.
Any help will be welcomed

Marisa

**Comment by SilviaHinojosa1983** [comment]
Hello

I am also having problems but with the config, here is the error

configure: error: could not find required version of GSL

**Comment by jpjoines** [comment]
Marisa89, did you download the zip file of the repository or clone it with git?

**Comment by Astahlke** [comment]
I had the same error as Marissa89 when cloning with git but was able to complete the make by installing from the zip file. Issue solved, but mystery remains. What's the difference?

**Comment by janxkoci** [comment]
Hi guys,

as an alternative, you can install fineRADstructure with `conda` manager from [Bioconda channel](https://bioconda.github.io/). It worked for me just fine.

I added the channel to my `conda` setup (see the link above), but you can also just use something like this:
`conda install -c bioconda fineradstructure`

Hope it helps ;)

**Comment by tommydevitt** [comment]
I [set up the Bioconda channel](https://daler.github.io/bioconda-docs/) as suggested but I get an error saying "The following packages are not available from current channels: fineradstructure". Not sure what's up.

**Comment by janxkoci** [comment]
@tommydevitt The setup you linked contains different order (priority) of channels as the current official website that I [linked](https://bioconda.github.io/) - it could cause e.g. unsupported version of C++ compiler to be installed. Also based on the presence of R channel, which has been dropped from official documentation some time ago I suspect the instructions you used are outdated.

You could for example try creating new environment and pulling packages from channels in the new order by using this command:
```
conda create --name fineradstr -c conda-forge -c bioconda fineradstructure
```

Then you activate the new environment with either `source activate fineradstr` or `conda activate fineradstr`, depending if you have set up `conda init`.

**EDIT:** According to [anaconda.org](https://anaconda.org/bioconda/fineradstructure) there is actually no build of fineradstructure for macOS. You could try Virtualbox or something else, but I found the MCMC step of finestructure quite memory-intensive.

**Comment by tommydevitt** [comment]
@janxkoci You're right that there isn't a build for macOS. I also tried on our Linux server and couldn't get it to build using conda. But I was able to install a containerized version.
