### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by gubrins** [millanek/fineRADstructure#16]
Hi,

I'm trying to install fineRADstructure and after running the ./configure, when I run make I get this error:

`collect2: error: ld returned 1 exit status
Makefile:610: recipe for target 'finestructure' failed
make: *** [finestructure] Error 1`

Do you know why?

Thanks in advance!

**Comment by danjlawson** [comment]
What is your system?
There are several issues that I've seen recently.
1. Recent changes to MacOS compiler makes some optimization flags invalid, leading to "error: unknown FP unit 'sse'":
sed 's!-mfpmath=sse -msse -msse2 !!' Makefile.am > Makefile.am.new
mv Makefile.am.new Makefile.am

2. Updated versions of automake may make the configure script invalid. The solution is to recreate the required contents:aclocaltouch README
automake --add-missing
./configure
make
These are issues for OSX and may not be related to this problem.
Dan    On Friday, 16 April 2021, 11:50:19 BST, gubrins ***@***.***> wrote:  
 
 


Hi,

I'm trying to install fineRADstructure and after running the ./configure, when I run make I get this error:

collect2: error: ld returned 1 exit status Makefile:610: recipe for target 'finestructure' failed make: *** [finestructure] Error 1

Do you know why?

Thanks in advance!

**Comment by EveTC** [comment]
Hi Dan,

I am having to re-install fineRADStructure and it doesn seem to work anymore. I can get past the `./configure` fine but when I run `make` I get this error:

```g++ -I/pub28/eve/bin/miniconda3/envs/fineRADStructure/include -std=c++0x -g -O2  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/pub28/eve/bin/miniconda3/envs/fineRADStructure/lib -Wl,-rpath-link,/pub28/eve/bin/miniconda3/envs/fineRADStructure/lib -L/pub28/eve/bin/miniconda3/envs/fineRADStructure/lib -o RADpainter RADpainter-tagPainter.o RADpainter-paintSql.o RADpainter-utils.o RADpainter-hapsFromVCF.o RADpainter-gzstream.o -L/pub28/eve/bin/miniconda3/envs/fineRADStructure/lib -lgsl -lgslcblas -lm
RADpainter-gzstream.o: In function `gzstreambuf::underflow()':
/pub28/eve/bin/miniconda3/envs/fineRADStructure/bin/fineRADstructure/gzstream.cpp:97: undefined reference to `gzread'
RADpainter-gzstream.o: In function `gzstreambuf::open(char const*, int)':
/pub28/eve/bin/miniconda3/envs/fineRADStructure/bin/fineRADstructure/gzstream.cpp:68: undefined reference to `gzopen'
RADpainter-gzstream.o: In function `gzstreambuf::close()':
/pub28/eve/bin/miniconda3/envs/fineRADStructure/bin/fineRADstructure/gzstream.cpp:79: undefined reference to `gzclose'
RADpainter-gzstream.o: In function `gzstreambuf::flush_buffer()':
/pub28/eve/bin/miniconda3/envs/fineRADStructure/bin/fineRADstructure/gzstream.cpp:114: undefined reference to `gzwrite'
collect2: error: ld returned 1 exit status
make: *** [RADpainter] Error 1```

I tried running your code above as well but it doesn't change. Any ideas? Cheers, Eve

**Comment by gubrins** [comment]
Thanks Dan for that, but now the error changed:

`CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.14 -I m4
/bin/sh: aclocal-1.14: command not found
make: *** [Makefile:560: aclocal.m4] Error 127`

**Comment by EveTC** [comment]
Hi @gubrins - I am not sure if this will help you but I found that it is available on anaconda (https://anaconda.org/bioconda/fineradstructure), and it installed without error.
 `conda install -c bioconda fineradstructure`

**Comment by gubrins** [comment]
Hi @EveTC 
Thanks for your help. I already tried that solution but when I run the finestructure function it appears an error. Don't worry, I installed it in a ubuntu machine and is working perfectly.

Thanks again!
