### ISSUE TITLE
"Invalid file!" error when using ./finestructure

### ISSUE THREAD

**Issue by sporrema** [millanek/fineRADstructure#21]
Hi,

I used edgardomortiz/fineRADstructure-tools to change my ipyrad files to finRADstructure compatible files. I am able to calculate the co-ancestry matrix without issue, but when I use the chunk.out file it generates I get the error "Invalid file!". I have attached my chunks.out file, I do not see any errors in it.

Thanks,
Megan

[spinosa_dnasp52.alleles.min2.finerad_chunks.out.zip](https://github.com/millanek/fineRADstructure/files/8063789/spinosa_dnasp52.alleles.min2.finerad_chunks.out.zip)

**Comment by danjlawson** [comment]
finestructure does not by default allow individual names that start with a number.  You may be able to solve this by running finestructure manually - for me "fs fs -X -Y ~/Downloads/spinosa_dnasp52.alleles.min2.finerad_chunks.out ~/Downloads/tmp.out" works correctly.  Its the "-X -Y" flags that tell it not to autodetect the format and hence assume names even if they begin with a number. However, my R scripts may not work as intended.

(fs is my maintained version of finestructure, but it is unlikely that the version in fineRADstructure would be different. location is https://people.maths.bris.ac.uk/~madjl/finestructure/finestructure.html )

**Comment by danjlawson** [comment]
finestructure does not by default allow individual names that start with a number.  You may be able to solve this by running finestructure manually - for me "fs fs -X -Y ~/Downloads/spinosa_dnasp52.alleles.min2.finerad_chunks.out ~/Downloads/tmp.out" works correctly.  Its the "-X -Y" flags that tell it not to autodetect the format and hence assume names even if they begin with a number. However, my R scripts may not work as intended.

(fs is my maintained version of finestructure, but it is unlikely that the version in fineRADstructure would be different. location is https://people.maths.bris.ac.uk/~madjl/finestructure/finestructure.html )

**Comment by sporrema** [comment]
That worked! Thanks!
