### ISSUE TITLE
Issue in drawing coancestry matrix

### ISSUE THREAD

**Issue by Lomousmishra** [millanek/fineRADstructure#28]
Hi Milan,
I am having issue with drawing co ancestry matrix using your fineradstructureplot.R script.
The issue is following:
> datamatrix<-dataraw[fullorder,fullorder]
Error in dataraw[fullorder, fullorder] : subscript out of bounds
I am using R version 3.6.1 inside conda, as earlier with R-4.2 also same issue occurred.
Please suggest me the possible solution for plotting.
Thanks,
Lomous

**Comment by danjlawson** [comment]
You normally get this error when the elements of "fullorder" are not in the row names and/or column names of your matrix "dataraw". Explanations include a) you start a name with a number or special character; b) there are "." characters, which are coerced to "_" in column names (you can just replace them; this could happen for other special characers) or c) you've done something bespoke with the data matrix construction and there is not a complete match. I recommend asking "all(fullorder %in% rownames(dataraw))" or similar to find the problem.

**Comment by Lomousmishra** [comment]
Thank you very much.
I modified the labels and the script worked for me.
Lomous
