### ISSUE TITLE
cannot get tree building to work

### ISSUE THREAD

**Issue by bnsacks** [millanek/fineRADstructure#3]
I can successfully run radpainter to make a coancestry matrix and then fineradstructure to make an mcmc.xml file, but I cannot seem to get the tree model to work.  Here is my command:

finestructure -m T -x 10000 abbrev.populations.haps_chunks.out fineRADstru4.mcmc.xml fineRADstruoutput4.tree.xml

A tree file is produced but with no data in it.  The slurm message is:

#  0%^H^H^H^H#  2%^H^H^H^H#  4%^H^H^H^H#  6%^H^H^H^H#  8%^H^H^H^H# 10%^H^H^H^H# 12%^H^H^H^H# 14%^H^H^H^H# 16%^H^H^H^H# 18%^H^H^H^H# 20%^H^H^H^H# 22%^H^H^H^H# 24%^H^H^H^H# 26%^H^H^H^H# 28%^H^H^H^H#$
Lgamma error: z=-6.99672e+08
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
/var/spool/slurmd/job5454124/slurm_script: line 7:  6780 Aborted                 finestructure -m T -x 10000 abbrev.populations.haps...

**Comment by lneaves** [comment]
I have the same issue and it still gave this error when I tried to run old input files that had run successfully on an older version (about a year ago).

**Comment by janxkoci** [comment]
I worked around this issue by using the original finestructure for tree-building step:

1. I installed finestructure (v2) using [this conda package](https://anaconda.org/bioconda/finestructure) from [Bioconda channel](https://bioconda.github.io/).
2. I then replaced `./finestructure` (the fineRADstructure version) with `fs fs` (the finestructure version)
3. It finished successfully and I could load the data into R to make plots.

I'm considering to re-run the second MCMC step in original fs just to see if it makes any difference.

I've also found finestructure v4 in [other channels](https://anaconda.org/search?q=finestructure), if somebody wants to test it out (there is no need to add the channels permanently).

Moreover there is a [fork repo of fineRADstructure](https://github.com/danjlawson/fineRADstructure) made by the original author of finestructure, with some fixes in the program - it could solve the problems, but it requires GSL 2.5 that I just couldn't make working.

Hope this helps

Jan

**Comment by bnsacks** [comment]
Hi Jan,
Thanks very much for passing this information on.  I will give it a try.
Best wishes,
Ben

**Comment by millanek** [comment]
Hello

I added Dan Lawson's putative fix for the tree building issue to my repo. Please try:
git pull
make
and then re-run the tree building.
Please, let me know if it helps.

Cheers
Milan

**Comment by janxkoci** [comment]
I cloned the repo to one of our servers and tried `./configure` but it fails because GSL >= 2.5 is required. I'll try to see if I can make it work this time...

**Comment by janxkoci** [comment]
So I finally figured out how to point to the right installation of GSL using:

```
./configure --with-gsl-prefix=/home/koci/bin/GSL --with-gsl-exec-prefix=/home/koci/bin/GSL
```
However I still get a build error:

```
...
checking for gsl-config... /home/koci/bin/GSL/bin/gsl-config
checking for GSL - version >= 0.2.5... no
*** Could not run GSL test program, checking why...
*** The test program compiled, but did not run. This usually means
*** that the run-time linker is not finding GSL or finding the wrong
*** version of GSL. If it is not finding GSL, you'll need to set your
*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point
*** to the installed location  Also, make sure you have run ldconfig if that
*** is required on your system
***
*** If you have an old version installed, it is best to remove it, although
*** you may also be able to get things to work by modifying LD_LIBRARY_PATH
configure: error: could not find required version of GSL
```

I noticed the version doesn't match exactly, as GSL reports **2.5** while the configure script checks for GSL >= **0.2.5**.

```
$ bash /home/koci/bin/GSL/bin/gsl-config --version
2.5
```
Could this be the problem?
