### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by lecorguille** [millanek/fineRADstructure#4]
Hi,
I plan to build a [bio]conda package for fineRADstructure
Can you create a tag release since it's more stable than commit hash?

Thanks

**Comment by millanek** [comment]
Hello
That's great, thank you. I have created the tag release for you.

Kind regards
Milan

**Comment by lecorguille** [comment]
Hop : https://anaconda.org/bioconda/fineradstructure
You can now if you want promote this method to install fineradstructure

**Comment by millanek** [comment]
Great!!! Thanks for making this available. Milan
