### ISSUE TITLE
finestructure Tree Building Issue (step 3)

### ISSUE THREAD

**Issue by crcardenas** [millanek/fineRADstructure#6]
I have a preliminary data set, which was run through the ipyrad pipeline without a reference genome. I used the alleles.loci outputfile with [fineRADstructure-tools](https://github.com/edgardomortiz/fineRADstructure-tools/blob/master/README.md), following their recommendations. I have attached the file here [fineradtools_converted.txt](https://github.com/millanek/fineRADstructure/files/3104911/fineradtools_converted.txt), since I am not sure if this is the issue. I will be using a reference genome in the future, but I am attempting some comparative analyses with this small data set first.

Any ways, I run step 1 and 2 fine, at least I think so. Step 2 does not give me any arguments other than that it has finished...

like so:

```
################################################### 100%
################################################### 100%
```
So I assume this has run correctly? 

Yet, when I run step 3 I keep getting outputs like this:
```
################################################### 100%
Lgamma error: z=-8.37464e+08
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
```

and 

```
################################################### 100%
Lgamma error: z=-2.47596e+08
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Aborted (core dumped)
```

The only thing different I can tell is that the Lgamma error changes... Perhaps it is related to the missingness output from step 1. I have a few samples that are well above 0.50 that I thought were supposed to be filtered out. I thought fineRADstructure-tools was supposed to clean up missing data... It certainly reduced my data set...

I may just run Stacks in the future, since I will be getting some paired end reads as opposed to this preliminary data set I have. But for the time being, I wonder if there is anything I can do to resolve this? I see that there was another person who had a similar issue but their question did not get resolved.

I appreciate your time!

**Comment by janxkoci** [comment]
Hi @crcardenas I worked around this issue by using original finestructure for the tree-building step - see https://github.com/millanek/fineRADstructure/issues/3#issuecomment-498643966 for more info.

**Comment by millanek** [comment]
Hello

I added Dan Lawson's putative fix for the tree building issue to my repo. Please try:
git pull
make
and then re-run the tree building.
Please, let me know if it helps.


Cheers
Milan

**Comment by pabuveery** [comment]
Hello! I had been receiving this same error, and ran the git pull command. Now I am receiving a Segmentation fault error instead. Has anyone encountered this issue? Thank you!

<img width="425" alt="Screen Shot 2020-04-30 at 6 53 02 PM" src="https://user-images.githubusercontent.com/45903483/80766615-d7d63280-8b13-11ea-9697-1428607131ed.png">
